#=====================#
#     PATHS SETUP     #
#=====================#
train_data_path: data/simple_stories_25k.txt
val_data_path: null
models_dir: models/
checkpoint_path: null
glove_embeddings_path: null

#==========================#
#     GENERAL SETTINGS     #
#==========================#
seed: 42
training_mode: statefull
use_accelerator: true

#=======================#
#     DATA SETTINGS     #
#=======================#
seq_len: 40
min_seq_len: 25
max_vocab_size: 20000

get_data_params:
  min_token_thresh: 15
  chunk_separator: "\n\n"
  preprocess: false
  entity_replacement: false
  add_special_tokens: true

val_split_enable: false
val_split_ratio: 0.15
val_split_shuffle: true
tokenizer_lowercase: false

#=========================#
#     TRAINING PARAMS     #
#=========================#
n_epochs: 50
batch_size: 256
enable_mixed_precision: true

early_stopping_epsilon: 0.0003
early_stopping_patience: 3
grad_clip_norm: 0.25

#=======================================#
#     PRETRAINED EMBEDDING SETTINGS     #
#=======================================#
use_glove_embeddings: false
glove_dim: 200

#======================#
#     MODEL PARAMS     #
#======================#
model_params:
 rnn_type: GRU
 embedding_dim: 350
 hidden_dim: 768
 num_layers: 2
 tie_weights: true
 
 emb_dropout_p: 0.25
 rnn_dropout_p: 0.25
 out_dropout_p: 0.3
 
 proj_nonlinearity: false
 freeze_pretrained_embeddings: true

#=================================#
#     LEARNING RATE SCHEDULER     #
#=================================#
lr_scheduler_params:
 factor: 0.5
 patience: 2
 threshold: 0.002

#==========================#
#     OPTIMIZER PARAMS     #
#==========================#
optimizer_params:
  lr: 0.002
  weight_decay: 0.00002