seed: 1212
use_accelerator: true
runs_dir: "runs/"

data:
  train_data_path: "data/processed/train.txt"
  val_data_path: "data/processed/val.txt"
  max_vocab_size: 25000
  tokenizer_lowercase: false

model:
  embedding_dim: 400
  hidden_dim: 400
  num_layers: 1
  tie_weights: true
  emb_dropout_p: 0.2
  rnn_dropout_p: 0.25
  out_dropout_p: 0.2

train:
  seq_len: 256
  batch_size: 128
  n_epochs: 80
  lr: 0.001
  weight_decay: 0.01
  eta_min: 0.00005
  early_stopping_patience: 4
  grad_clip_norm: 1.0
  enable_mixed_precision: true